edgexfoundry/edgex-compose

compose-builder/add-security.yml
releases/pre-release/docker-compose-pre-release-arm64.yml
releases/pre-release/docker-compose-pre-release.yml
releases/pre-release/taf/docker-compose-taf-arm64.yml
releases/pre-release/taf/docker-compose-taf-perf-arm64.yml
releases/pre-release/taf/docker-compose-taf-perf.yml
releases/pre-release/taf/docker-compose-taf.yml

Change `SECRETSERVICE_SERVER` to `SECRETSTORE_HOST` and
`SECRETSERVICE_TOKENPATH` to `SECRETSTORE_TOKENPATH`
Fixes: #11
env vars of proxy-setup is out-dated since new go-mod-secret version is used
Updated the env key names.
- [x ] No

fix(security): Update out-of-date envs of proxy-setup service

---

compose-builder/add-device-virtual.yml
releases/pre-release/docker-compose-pre-release-arm64.yml
releases/pre-release/docker-compose-pre-release-no-secty-arm64.yml
releases/pre-release/docker-compose-pre-release-no-secty.yml
releases/pre-release/docker-compose-pre-release.yml
releases/pre-release/taf/docker-compose-taf-arm64.yml
releases/pre-release/taf/docker-compose-taf-no-secty-arm64.yml
releases/pre-release/taf/docker-compose-taf-no-secty.yml
releases/pre-release/taf/docker-compose-taf-perf-arm64.yml
releases/pre-release/taf/docker-compose-taf-perf-no-secty-arm64.yml
releases/pre-release/taf/docker-compose-taf-perf-no-secty.yml
releases/pre-release/taf/docker-compose-taf-perf.yml
releases/pre-release/taf/docker-compose-taf.yml

device-virtual docker container is using a R/W filesystem.
device-virtual will have read-only permission.
Close #32
Resolve edgexfoundry/device-virtual-go#168

fix: Add read-only flag to device-virtual

---

compose-builder/add-security.yml
compose-builder/docker-compose-base.yml
releases/pre-release/docker-compose-pre-release-arm64.yml
releases/pre-release/docker-compose-pre-release-no-secty-arm64.yml
releases/pre-release/docker-compose-pre-release-no-secty.yml
releases/pre-release/docker-compose-pre-release.yml
releases/pre-release/taf/docker-compose-taf-arm64.yml
releases/pre-release/taf/docker-compose-taf-no-secty-arm64.yml
releases/pre-release/taf/docker-compose-taf-no-secty.yml
releases/pre-release/taf/docker-compose-taf-perf-arm64.yml
releases/pre-release/taf/docker-compose-taf-perf-no-secty-arm64.yml
releases/pre-release/taf/docker-compose-taf-perf-no-secty.yml
releases/pre-release/taf/docker-compose-taf-perf.yml
releases/pre-release/taf/docker-compose-taf.yml

Not all services have the user specified explicitly.
The CIS/DBS tool expects that when running as root that be explicit.
All services, except Kong, have the user specified explicitly.
Kong runs as `kong` user, but doesn't expose it so it can be used in the compose file.

refactor: Specify user explicitly for all services

---

compose-builder/add-security.yml
releases/pre-release/docker-compose-pre-release-arm64.yml
releases/pre-release/docker-compose-pre-release.yml
releases/pre-release/taf/docker-compose-taf-arm64.yml
releases/pre-release/taf/docker-compose-taf-perf-arm64.yml
releases/pre-release/taf/docker-compose-taf-perf.yml
releases/pre-release/taf/docker-compose-taf.yml

- mount /tmp/edgex/secrets/ to be writable volume
Closes: #40
Currently, the /tmp/edgex/secrets/ is not mounted as volume and thus it is read-only as the container itself is read-only system.
Mount the volume `/tmp/edgex/secrets` folder to be writable.
- [x ] No
This PR should be merged together with the edgex-go PR …

feat(security): Update consul's volume on secrets folder to be writable

---

compose-builder/Makefile
compose-builder/README.md
compose-builder/add-ui.yml
compose-builder/stand-alone-ui.yml
docker-compose-pre-release-ui.yml

Currently the UI is run from stand-alone compose file after the EdgeX stack is up and running
Now a user has the option of including the UI in there single EdgeX custom compose file. Note the standard release compose files still don not include the UI, thus we still have the stand-alone UI compose files.
no

refactor: Enable adding UI service when generating a compose file

---

compose-builder/Makefile
compose-builder/README.md

`make ui-down` fails due to YAML file no longer exists
Documentation for UI YAML file incorrect.
`make ui-down` now works properly
Documentation for UI YAML file corrected.

fix: Update the ui-down target to use new UI compose files.

---

compose-builder/Makefile
compose-builder/README.md
compose-builder/add-asc-http-export-secure.yml
compose-builder/add-asc-http-export.yml
compose-builder/add-asc-mqtt-export-secure.yml
compose-builder/add-asc-mqtt-export.yml
compose-builder/add-security.yml
compose-builder/add-taf-app-services-secure.yml
compose-builder/add-taf-app-services.yml
docker-compose-pre-release-arm64.yml
docker-compose-pre-release.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

- add edgex-sys-mgmt and app-service-rule-engine into security yaml for them to be waiting on consul-bootstrapper
Closes: #52
no waiting mechanism for both services of `system-management` and `app-service-rule-engine` yet
Add waiting mechanism for both services of `system-management` and `app-service-rule-engine`
- [x ] No
N/A
Are there any specific instructions or things that should be known prior to …

feat(security): integrating consul token for edgex-sys-mgmt and app-services

---

compose-builder/Makefile
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf.yml

Fix the issue on device-virtual and device modbus for TAF tests failed to
start them as they lost the executables of services in command section
Fixes: #64
Currently TAF test fails to start device-virtual/device-modbus as they lost the executables from the command section when run in security mode.
Added the lost commands via extending them from the script and keeping the special PLACE_HOLDER in parameter snippet.
- [x ] No
Are there any new imports or modules? If so, what are …

fix(security): Fix TAF failing to start device-virtual

---

Makefile
README.md
compose-builder/Makefile
compose-builder/add-device-modbus.yml
compose-builder/add-service-secure-template.yml
compose-builder/add-taf-app-services-secure.yml
compose-builder/asc-common.env
compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.
ZMQ is the default MessageBus
Redis is now the default MessageBus
BREAKING CHANGE: All services receiving Event must now be configured to use Redis as the MessageBus

feat: Switch to Redis as the default MessageBus

---

compose-builder/add-security.yml
docker-compose-arm64.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

- adding env. override for consul's route
- adding volume share between proxy-setup and consul for bootstrap acl token
Closes: #71
currently there is no consul service route in Kong
added consul service route in Kong through proxy-setup and this depends on `edgex-go` PR https://github.com/edgexfoundry/edgex-go/pull/3391 and enabling Kong's Admin API PR https://github.com/edgexfoundry/edgex-compose/pull/60 in this repo.
- [x ] No
Are there any new imports or modules? If so, what …

feat(security): Update compose for adding consul header into Kong's route

---

compose-builder/Makefile
compose-builder/add-service-secure-template.yml
docker-compose-arm64.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Fix the missing Kong route of `device-modbus` on TAF test using env `ADD_PROXY_ROUTE` of `proxy-setup`
Fixes: #100
kong route seems to be missing based on the error log of TAF testing on `device-modbus` through Kong.
Added kong route through env `ADD_PROXY_ROUTE` for device-modbus.
- [x ] No

fix(security): Fix the issue of missing device-modbus's Kong route

---

compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Code Data subscribe is enabled and receives Events it published and already persisted causing a duplicate ID error which causes TAF tests to fail.
This is temporary disable subscribe until determine proper resolution for the issue of Core Data receiving the messages that it publishes.

refactor: Disable Core Data subscribe to MessagBus

---

compose-builder/get-api-gateway-token.sh

Closes #114 
Fixes minor typo that sets the "unique" ID for new JWT's to the literal string "uuidgen"

fix: Missing backtick to retrieve unique id from uuidgen

---

compose-builder/Makefile
compose-builder/README.md
compose-builder/add-secure-redis-messagebus.yml
compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

**This PR is dependent on https://github.com/edgexfoundry/edgex-go/pull/3537 merged and images built**
Kuiper has no knowledge of the credentials when using Secure MessageBus
Volume mount the Kuiper Edgex config file with credentials that is created by Secret Store Setup

feat: Add Secure MessageBus credentials injection for Kuiper

---

compose-builder/add-security.yml
docker-compose-arm64.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

closes 
Signed-off-by: lenny <leonard.goodell@intel.com>
Kong caches IP address for ~5 mins before the cache is invalidated
When service IP changes, the service is not accessible via Kong for ~5 mins
Kong now configured cache IP address for only 1 second before the cache is invalidated
Now when service IP changes, the service is accessible via Kong after only 1 sec.

fix: Set KONG_DNS_VALID_TTL: '1' so Kong caches IP for only 1 sec

---

compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

SysMgmtAgent gets `permission denied` on CentOS for access to docker
This resolves permissions issue on CentOS for SysMgmtAgent access to docker

fix: Add label:disable to security_opt for SysMgmtAgent

---

compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Core Data subscribe is disable with env override
Core Data subscribe no longer disable with env override

refactor: Remove Core Data override for MESSAGEQUEUE_SUBSCRIBEENABLED

---

Makefile
compose-builder/Makefile

Signed-off-by: Anthony Casagrande <anthony.j.casagrande@intel.com>
- **[N/A]** Tests for the changes have been added (for bug fixes / features)
- **[N/A]** Docs have been added / updated (for bug fixes / features)
Options such as `arm64` and `no-secty` are not available for tab-completion.
> _Note: `<TAB>` indicates the user pressing the Tab key on their keyboard._
```shell
user@machine:projects/edgex-compose$ make <TAB>
clean                 get-consul-acl-token  portainer             pull-ui               
down                  get-token             portainer-down        run                   
down-ui               help                  pull                  run-ui  
```
```shell …
```

feat(make): add tab-completion for all custom options

---

compose-builder/Makefile

running make down fails due to add-device-random.yml file previously removed, but not removed from down target
make down no longer fails

fix: [Ireland] remove device-random from down target

---

compose-builder/Makefile

running `make down` fails due to `add-device-random.yml` file previously removed, but not removed from `down` target
`make down` no longer fails

fix: Remove device random from down make target

---

compose-builder/README.md

Signed-off-by: lenny <leonard.goodell@intel.com>
Description for app-rfid-llrp-inventory compose file is slightly wrong as it starts with `Application Service Configurable **extending**` rather than `Application Service **extending**`
Description for app-rfid-llrp-inventory compose file corrected.

fix: Correct description for app-rfid-llrp-inventory compose file

---

README.md
compose-builder/Makefile
compose-builder/README.md
compose-builder/add-asc-sample.yml
docker-compose-no-secty-with-ui-arm64.yml
docker-compose-no-secty-with-ui.yml

asc-sample is not an option 
asc-sample is now an option and is included in the non-secure with UI compose files  so the UI can use it to allow users to manipulate the configurable pipeline.

feat: Add asc-sample option and include in no-secty-with-ui built compose files

---

compose-builder/Makefile
compose-builder/add-taf-device-services-mods.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf.yml

Generation of secure TAF function compose files is missing the  `-cp` option.
Generation of secure TAF function compose files now have the  `-cp` option.

fix: Add -cp option to call to gen_secure_compose_ext.sh in Makefile for TAF device services

---

Makefile
README.md
compose-builder/Makefile
compose-builder/README.md

Clean commands remove ALL un-used volumes, containers and networks even if not part of the Edgex stack
Clean commands now only remove un-used volumes, containers and networks that are part of the Edgex stack

feat: Change clean commands to just clean EdgeX volumes, containers and networks

---

compose-builder/add-security.yml
docker-compose-arm64.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Closes #3680
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.
API gateway supports "intermediate" level of cipher suites.
- #3680
API gateway supports "modern" cipher suite and TLSv1.3 only.

feat(security): Enable modern cipher suite / TLSv1.3 only

---

compose-builder/Makefile

Now the security services are configured properly when the `ds-camera` option is used.
fixes #181
run `make run ds-camera` 
Check Device Camera logs to verify it successfully created the secrets client. i.e didn't fail to startup due to not finding it's Vault token

fix: Use correct service key for Device Camera

---

compose-builder/README.md

README update to let devs know they must use docker-compose 1.27.2
**N/A**

docs: Update builder README with note on using docker-compose 1.27.2

---

compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-ui-arm64.yml
docker-compose-no-secty-with-ui.yml
docker-compose-no-secty.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Note that secure compose does this via entry point script. Command
setting added will be overridden in secure mode by the entry point
script.
fixes #186
1. run docker-compose up on non-secure compose file
2. Change setting for any service in Consul
3. run docker-compose down
4. run docker-compose up
5. verify the changed setting in Consul is still changed
6. run docker-compose down -v (cleans volumes)
6. repeat above steps with secure compose file

fix: Enable Consul persistence in non-secure compose

---

compose-builder/Makefile
compose-builder/README.md
compose-builder/add-asc-external-mqtt-trigger.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf.yml

Add new app-service: app-service-external-mqtt-trigger for [edgexfoundry/edgex-taf issue #514](https://github.com/edgexfoundry/edgex-taf/issues/514).
1. Build app-service images that contain external-mqtt-trigger profile.
2. Deploy service using the compose file.
3. Subscribe both topics "external-request": SubscribeTopics in Trigger and "edgex-export": Topic in Pipeline Function.
4. Publish a message "test message" to the topic "external-request" which is defined in …

feat: Add new app-service: app-service-external-mqtt-trigger for TAF test

---

Jenkinsfile

This PR implements new functionality to archive any 3rd party docker images to nexus release (10002) repository. The new stage added will only run when the `ARCHIVE` jenkins build parameter is passed in. This stage will only need to be triggered on LTS releases and can be done with anyone with Jenkins build permission.
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

ci: add stage to archive 3rd party images from compose file

---

compose-builder/add-app-rfid-llrp-inventory.yml

fix: [Kamakura] Add missing volume for LLRP Inventory app service's data

---

Jenkinsfile

Fix issue with new Jenkins update where builds triggered by webhooks no longer have parameters set in the environment.
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

ci: fix issue with ARCHIVE param

---

compose-builder/add-mqtt-messagebus.yml
compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

closes #215
NOTE: eKuiper has a BUG with the MQTT connection. Issue files here: https://github.com/lf-edge/ekuiper/issues/1174
run secure compose file (`docker-compose.yml`)
create ekuiper stream
```
{
"sql": "create stream EdgexStream () WITH (FORMAT=\"JSON\", TYPE=\"edgex\")"
}
```
create ekuiper rule
```
{
"id": "ruleEdgexSinkApp",
"sql": "SELECT meta(*) as m, Int8 From EdgexStream WHERE meta(deviceName) = \"Random-Integer-Device\" AND isNull(Int8) = false", …
```

fix: Update eKuiper env overrides to those for 1.4.x shared connection

---

compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

It has been determined that exposing the Consul port externally is unsafe,
despite Consul authentication, because the Consul access token
is exposed over the wire.
Refs: 685de56a36267c0adb07867b2eda848eadd86500
Closes #190
Closes https://github.com/edgexfoundry/edgex-go/issues/3744
`make run` ensure everything comes up.

fix(security)!: Revert exposing Consul port externally

---

compose-builder/add-mqtt-messagebus.yml
compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Run edgex stack with **Redis** MessageBus un-secure
Create stream and rule
Verify eKuiper logs don't have error connecting to MessageBus 
Run edgex stack with **MQTT** MessageBus un-secure
Create stream and rule
Verify eKuiper logs don't have error connecting to MessageBus

fix: Update eKuiper environment variables to not use Shared connection by default and fix MQTT issue

---

compose-builder/tui-generator.sh

provide a terminal based UI using whiptail to generate a
custom `docker-compose.yml` file. The bash script collects the
necessary selections from a defined Usage Flow and generates the
compose file by calling the `make compose <selection>` command.
Aforementioned Usage Flow is documented in #225 
Signed-off-by: Shantanoo 'Shan' Desai <shantanoo.desai@gmail.com>
```bash
cd compose-builder/
chmod +x tui-generator.sh
./tui-generator.sh
```
__OS/Distro__: GNU/Linux Manjaro Rolling
__whiptail version__: `whiptail (newt): …

feat: add terminal UI to generate compose files

---

compose-builder/README.md
compose-builder/tui-generator.sh

Also added missing `asc-metrics` to the tui-generator.sh

feat: Update the README to reference TUI Generator

---

compose-builder/.env
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

**Note:** 
- Redis 7 breaks the PubSub auth when in secure mode. Staying with 6.x for now.
- Postgres 14 breaks Kong (2.6 & 2.8) bootstrapping. Staying with 13.x for now.
Run stack in secure mode
Verify all service bootstrap properly
Verify /ping via API Gateway

build: Update to latest 3rd party version that don't break

---

compose-builder/tui-generator.sh

wrong usage of inserting selections via whiptail UI in bash
clubbed them into a single string with new-line character at
index 0. An optimal way was to use `readarray -t <VAR> < <..`
instead of `<VAR>+=`. This PR fixes the issue.
A potential benefit would be to make the TUI bash script more
extensible for selected individual service names
(e.g. using `for`/`case`) for future usage / tweaks.
Closes #248
Signed-off-by: Shantanoo 'Shan' Desai <shantanoo.desai@gmail.com>

fix(TUI): use correct bash usage for selection arrays

---

compose-builder/Makefile
compose-builder/README.md

Useful if the generated compose file has been modified and need to rerun with the `-p edgex` options that are used with `make run`.
from compose builder do the following:
- remove old docker-compose.yml file if it exists
- Run `make up`
- Verify command resulted in File Not Found error
- Run `make gen no-secty ds-virtual`
- Run `make up`
- Verify service all started under the `edgex` stack

feat: Add "up" command to run the generated docker compose file

---

compose-builder/add-security.yml
compose-builder/get-consul-acl-token.sh
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

closes: #268
Signed-off-by: Valina Li <valina.li@intel.com>

feat: add management token env

---

compose-builder/Makefile
compose-builder/gen-header
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Needed for future PRs, but might also address #251
Ran `make build` and verified only change to generated and committed compose files is the  Copyright year
Run `make gen ds-onvif-camera ds-modbus ds-llrp as-llrp asc-metrics ds-mqtt mqtt-broker asc-http asc-mqtt 
asc-sample` using this branch and rename the file.
Run `make gen ds-onvif-camera ds-modbus ds-llrp as-llrp asc-metrics ds-mqtt mqtt-broker asc-http asc-mqtt 
asc-sample` using `main` branch compare to …

refactor: Pass variables to docker compose as exported environment vars

---

compose-builder/.env
compose-builder/Makefile
compose-builder/README.md
compose-builder/add-app-rfid-llrp-inventory.yml
compose-builder/add-asc-external-mqtt-trigger.yml
compose-builder/add-asc-http-export.yml
compose-builder/add-asc-metrics-influxdb.yml
compose-builder/add-asc-mqtt-export.yml
compose-builder/add-asc-sample.yml
compose-builder/add-delayed-start-services.yml
compose-builder/add-device-bacnet.yml
compose-builder/add-device-camera.yml
compose-builder/add-device-coap.yml
compose-builder/add-device-gpio.yml
compose-builder/add-device-grove.yml
compose-builder/add-device-modbus.yml
compose-builder/add-device-mqtt.yml
compose-builder/add-device-onvif-camera.yml
compose-builder/add-device-rest.yml
compose-builder/add-device-rfid-llrp.yml
compose-builder/add-device-snmp.yml
compose-builder/add-device-usb-camera.yml
compose-builder/add-device-virtual.yml
compose-builder/add-security.yml
compose-builder/add-taf-app-services.yml
compose-builder/docker-compose-base.yml
compose-builder/get-api-gateway-token.sh
compose-builder/get-consul-acl-token.sh
compose-builder/upload-api-gateway-cert.sh

Also cleaned up use of DEV variable
closes #197
With this branch..
Run `make build` from compose builder.
Verify none of the generated compose file(TAF included) changed.
Build local docker images for edgex-go, UI, ASC and Device Virtual
run `make run ds-virtual asc-http asc-mqtt asc-sample dev app-dev device-dev ui-dev`
Verify all edgex services running are local `0.0.0-dev` versions
Verify all services are running properly
run `make get-token`
Verify token …

feat: Add ui-dev and device-dev options

---

Makefile
README.md
compose-builder/Makefile
compose-builder/README.md

closes #272
README's have been updated
From clean system (EdgeX not running with all EdgeX containers, volumes and networks removed)
With `docker-compose` installed and `compose V2` installed
- run `make run no-secty` 
- verify `docker-compose` was used and all services run fine
- Rename `docker-compose` so it isn't found
- run `make run no-secty` 
- verify `docker compose` was used and all services run fine
- run `make clean`
- verify `docker compose` was used
- Verify all …

feat: Add optional support to use compose V2

---

compose-builder/add-secure-mqtt-messagebus.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml

Closes:#285
Signed-off-by: intel <joshua.silverio@intel.com>
Can gen compose file 
- make gen dev ds-virtual mqtt-bus
- make up
- check kuiper container and app rules engine container to see the mqtt-bus connection success and flowing data
- shell into kuiper container and cat /kuiper/etc/sources/edgex.yaml to confirm usr/pass of mqtt-bus is configured correctly

fix(security): eKuiper env variables and volumes for secure mqtt

---

compose-builder/get-api-gateway-token.sh

Run secure stack
Run `make get-token`
Verify no error message, just token displayed.

fix: Correct get-api-gateway-token.sh script for when DEV env is empty

---

compose-builder/add-device-gpio.yml

This PR brings device-gpio in line with the documented, approved port number, 59994 instead of 59910.
```
make run ds-gpio (in compose-builder)
curl -ki http://localhost:59994/api/v2/ping
```

fix: Move GPIO service to approved documented port

---

compose-builder/Makefile

fix: Use correct service key and exe name for ds-snmp

---

Makefile
README.md
compose-builder/Makefile
compose-builder/README.md
compose-builder/add-mqtt-broker.yml
compose-builder/add-secure-mqtt-broker.yml
compose-builder/add-taf-device-services-mods.yml
compose-builder/tui-generator.sh
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

BREAKING CHANGE: Old docker-compose tool no longer supported. Must use docker compose CLI command. See README for details.
closes #315
**TBD**

refactor!: Change to only support compose V2 to generate and run compose files

---

compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

ZMQ was previously removed, but the port export was missed.
closes #325

refactor: Remove un-needed port export on Core Data that was for ZMQ

---

compose-builder/add-security.yml
compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

closes #320
Note this PR is dependent on https://github.com/edgexfoundry/edgex-go/pull/4300 so that this works properly in secure mode.
TBD
Run the following compose builder commands from this branch 
- `make pull`
- `make run no-secty`
- Verify `core-common-config-bootstrapper service` logs show the following.
```
level=INFO ts=2023-01-23T15:12:28.3485979Z app=core-common-config-bootstrapper source=main.go:52 msg="Core Common Config is starting"
level=INFO …
```

feat: Add core-common-config-bootstrapper service to compose files

---

compose-builder/add-security.yml

Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
1. run `make docker` in edgex-go with the updated changes for common config
2. run `make run dev` from compose builder
3. ensure the common config was loaded from the configuration.yaml file

fix: add configuration.yaml env override to the common config entrypoint

---

compose-builder/add-device-gpio.yml

revert: Undo the override of Device GPIO's port

---

compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

BREAKING CHANGE: remove notifications dependency from metadata
metadata will send system events to message queue directly instead of notifications REST call in v3.
closes #339
Signed-off-by: Chris Hung <chris@iotechsys.com>

feat!: remove notifications dependency from metadata

---

compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

TBD
From compose builder run `make gen no-secty ds-virtual`
Modify generated compose file to add `KUIPER__BASIC__DEBUG: "true"` to eKuiper environment
Run `make up`
From Postman or curl create a stream by posting the following to `http://localhost:59720/streams`
```
{
"sql": "create stream EdgexStream () WITH (FORMAT=\"JSON\", TYPE=\"edgex\")"
}
```
From Postman or curl create a rule by posting the following to `http://localhost:59720/rules`
```
{
"id": "ruleBool",
"sql": "SELECT bool FROM EdgexStream where bool = true",
"actions": [
{ …
```

refactor: Consume change to add base topic to rules-engine events topic

---

compose-builder/add-app-rfid-llrp-inventory.yml
compose-builder/add-delayed-start-services.yml
compose-builder/add-nats-messagebus.yml
compose-builder/add-secure-mqtt-broker.yml
compose-builder/add-secure-mqtt-messagebus.yml
compose-builder/add-secure-redis-messagebus.yml
compose-builder/add-security.yml
compose-builder/add-service-secure-template.yml
compose-builder/add-taf-app-services-secure.yml
compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

BREAKING CHANGE: This was previously add for CentOS, but is not causing issuse with move to `docker compose V2`. Users that require this for CentOS will need to customize the compose files appropraitly.
closes #329
Run `make build` from compose builder.
Verify the generated compose files no longer have `bind` for `selinux: z`

fix: Remove :z and ,z from all named volumes

---

compose-builder/docker-compose-base.yml

When starting the EdgeX framework, a "docker volume ls" command will show three hex-string named volumes that are created as a result of VOLUME declarations in the base image. These volumes correspond to /kuiper/etc, /kuiper/log, and /kuiper/plugins.
This commit explictly mounts named volumes to these locations to stop docker from creating randomly named fill-in volumes.
Before fix:
- make clean
- make run
- docker volume ls
- (observe placeholder volumes)
After fix:
- make clean
- make run
- docker volume ls
- (observe placeholder volumes are replaced with named volumes)

fix: Eliminate unnamed Kuiper volumes

---

compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

feat: Add common environment overrides to Common Config service

---

compose-builder/add-service-secure-template.yml
compose-builder/gen_secure_compose_ext.sh

Fixes issue where some device service containers don't have the dumb-init tool, which us used as the shell intepreter for the wait_install.sh secure bootstrapping script.  The override forces use of /bin/sh.
Run make run with all device services.  Note that device-bacnet container has a missing file that is causing nested startup issues.

fix: Some device service containers dont' have dumb-init

---

compose-builder/Makefile

Updated Makefile to run delayed-started generation script for support services to make sure these serivces are delayed-startable
Fixes: #364
- [x ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- docker build the latest edgex-go and ensure the fix in this PR is in there: https://github.com/edgexfoundry/edgex-go/pull/4509 
- use …

fix: added missing delayed started spiffe volume for support services

---

compose-builder/add-security.yml
compose-builder/add-service-secure-template.yml
compose-builder/add-taf-app-services-secure.yml
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

BREAKING CHANGE: Add EDGEX_ prefix to ADD_SECRETSTORE_TOKENS, ADD_REGISTRY_ACL_ROLES, ADD_KNOWN_SECRETS, ADD_PROXY_ROUTE, and IKM_HOOK variables
https://github.com/edgexfoundry/edgex-docs/pull/1027
Build https://github.com/edgexfoundry/edgex-go/pull/4514 (make docker)
make run dev (add a few extra services like ds-rest ds-virtual)

refactor(security)!: Prefix security related env vars with EDGEX_

---

compose-builder/add-secure-device-mqtt.yml

```
make run ds-mqtt mqtt-bus
```
Without this fix, device-mqtt will fail trying to cred "credentials" secret instead of "message-bus" secret.

fix: CREDENTIALSPATH changed to CREDENTIALSNAME

---

compose-builder/add-delayed-start-services.yml

go-mod-bootstrap only allows registration of HTTP healtchecks with consul, which will not work for this service, as it requires clients have a client TLS certificate
```
make delayed-start ds-virtual
```
Thence, go to http://localhost:8500/ui/dc1/services and verify no failing health check for edgex-security-spiffe-token-provider

fix: Don't register spiffe token provider service

---

compose-builder/Makefile

The device USB camera uses different normal executable like docker entrypoint shell script, so update the Makefile to adapt to this case
Fixes: #377
1. clone this pr
2. make sure you have an equivalent usb camera plug into the system
3. make clean
4. make pull ds-usb-camera
5. make run ds-usb-camera
6. observe the log of the ds-usb-camera service starts up correctly with `docker logs edgex-device-usb-camera | grep docker-entrypoint`

fix: change the ds-usb-camera executable to be docker-entrypoint-script

---

compose-builder/add-device-gpio.yml

fix: [minnesota] Correct GPIO Port to be same as documented

---

compose-builder/Makefile
compose-builder/README.md
compose-builder/add-device-bacnet-ip.yml
compose-builder/add-device-bacnet-mstp.yml
compose-builder/gen_secure_compose_ext.sh
compose-builder/tui-generator.sh

fix: #397 
`make run ds-bacnet-ip`
Verify if the BACnet device service runs normally.

fix: Change service key from device-bacnet to device-bacnet-ip

---

compose-builder/Makefile
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml

From compose builder run `make run ds-onvif-camera ds-usb-camera ds-bacnet-ip ds-modbus ds-mqtt ds-rest ds-snmp ds-virtual ds-llrp ds-coap ds-gpio asc-http asc-mqtt asc-sample asc-metrics as-llrp asc-ex-mqtt mqtt-broker`
For each of the above services (expect mqtt-broker) verify `https://localhost:8443/<service-key>/api/v3/ping` results in 200 response.

fix: [Minnesota] Set EXTRA_PROXY_ROUTE_LIST for all add on services except Device Virtual

---

compose-builder/Makefile
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml

fixes #405
From compose builder run `make run ds-onvif-camera ds-usb-camera ds-bacnet-ip ds-modbus ds-mqtt ds-rest ds-snmp ds-virtual ds-llrp ds-coap ds-gpio asc-http asc-mqtt asc-sample asc-metrics as-llrp asc-ex-mqtt mqtt-broker`
For each of the above services (expect mqtt-broker) verify `https://localhost:8443/<service-key>/api/v3/ping` results in 200 response.

fix: [Main] Set EXTRA_PROXY_ROUTE_LIST for all add on services except Device Virtual

---

compose-builder/add-security.yml
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

refactor: Remove unneeded edgex-kong network alias

---

compose-builder/Makefile
compose-builder/add-security.yml
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Closes #434
`make build` by `Docker Compose version v2.15.1`

fix: Add "restart: always" in security-proxy-setup service

---

compose-builder/Makefile
compose-builder/add-security-proxy.yml
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-keeper-arm64.yml
taf/docker-compose-taf-keeper.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus-keeper-arm64.yml
taf/docker-compose-taf-mqtt-bus-keeper.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
taf/docker-compose-taf-no-secty-mqtt-bus.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Closes #449 Add core-keeper to the TAF compose file which using Consul as registry service
Closes #439 Remove unneeded ROUTES_* environment variables

fix: Add core-keeper to the TAF compose file which using Consul as registry service

---

README.md
docker-compose-postgres-no-secty-arm64.yml
docker-compose-postgres-no-secty.yml

Resolves #453. Add temp docker compose files to test Postgres as the supported database.

feat: Add temp docker compose files to test Postgres as database

---

Makefile
README.md
compose-builder/Makefile
compose-builder/README.md
compose-builder/add-delayed-start-services.yml
compose-builder/add-security.yml
docker-compose-arm64.yml
docker-compose-portainer.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose-zero-trust-arm64.yml
docker-compose-zero-trust.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-keeper-arm64.yml
taf/docker-compose-taf-keeper.yml
taf/docker-compose-taf-mqtt-bus-arm64.yml
taf/docker-compose-taf-mqtt-bus-keeper-arm64.yml
taf/docker-compose-taf-mqtt-bus-keeper.yml
taf/docker-compose-taf-mqtt-bus.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Closes #452 
Feat: Run Edgex in a rootless docker environment for added security
Docs updates are to come soon
Test on ubuntu linux with both a rootless docker environment, and a rootful docker environment. Start edgex using make run, and start portainer with make portainer from within the compose-builder folder. 
```bash
token=$(make get-token)
```
```bash
curl -k -H "Authorization: Bearer $token" https://localhost:8443/core-data/api/v3/ping
```
```bash
curl -H "Authorization: Bearer $token" http://localhost:59880/api/v3/event/device/name/Random-Integer-Device
```
```bash
curl -H "Authorization: Bearer $token" http://localhost:59882/api/v3/device/name/Random-Integer-Device
```
```bash
curl -H "Authorization: Bearer $token" …
```

feat: Docker rootless

---

Makefile
compose-builder/Makefile

Closes #460 
docs change not required as this is a bug fix. 
Navigate to the compose-builder folder. Make sure you are running in a rootless docker environment. Run `make portainer`. After portainer has started run `docker inspect portainer`. Make sure the docker socket bind mount is in the user's space instead of the sudo docker socket location. Navigate to the portainer localhost web page and make sure it can connect to the docker socket and see other running containers.

fix: portainer docker rootless

---

README.md
docker-compose-postgres-no-secty-arm64.yml
docker-compose-postgres-no-secty.yml

Relates to edgexfoundry/edgex-go/issues/4877. Modify keeper service to use postgres as database in non-sec compose files.

fix: Modify keeper service to use postgres as database

---

compose-builder/Makefile

refer to https://github.com/edgexfoundry/edgex-go/issues/4832

fix: Export MQTT message bus env variables for Keeper

---

compose-builder/add-security.yml
compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose-zero-trust-arm64.yml
docker-compose-zero-trust.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

BREAKING CHANGE: the cron scheduler name and key changed
Replace the old Scheduler service with the new cron Scheduler service

refactor: Replace old Scheduler service with cron Scheduler service

---

compose-builder/Makefile
compose-builder/add-secure-postgres.yml
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose-zero-trust-arm64.yml
docker-compose-zero-trust.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Fixes #482. Remove POSTGRES_PASSWORD variable in compose file.

fix: Remove POSTGRES_PASSWORD variable in compose file

---

compose-builder/add-security.yml
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose-zero-trust-arm64.yml
docker-compose-zero-trust.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Fixes #484. Add CLIENTS_SECURITY_PROXY_AUTH_HOST env var with security enabled.

fix: Add CLIENTS_SECURITY_PROXY_AUTH_HOST env var

---

compose-builder/Makefile

fix: Add support-scheduler back to delayed-start function

---

compose-builder/add-security.yml
compose-builder/common-security.env
docker-compose-arm64.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose-zero-trust-arm64.yml
docker-compose-zero-trust.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

Fixes #490. Add CLIENTS_SECURITY_SECRETSTORE_SETUP_HOST env to compose files.

feat: Add CLIENTS_SECURITY_SECRETSTORE_SETUP_HOST env

---

compose-builder/add-security.yml
compose-builder/docker-compose-base.yml
docker-compose-arm64.yml
docker-compose-no-secty-arm64.yml
docker-compose-no-secty-with-app-sample-arm64.yml
docker-compose-no-secty-with-app-sample.yml
docker-compose-no-secty.yml
docker-compose-with-app-sample-arm64.yml
docker-compose-with-app-sample.yml
docker-compose-zero-trust-arm64.yml
docker-compose-zero-trust.yml
docker-compose.yml
taf/docker-compose-taf-arm64.yml
taf/docker-compose-taf-no-secty-arm64.yml
taf/docker-compose-taf-no-secty.yml
taf/docker-compose-taf-perf-arm64.yml
taf/docker-compose-taf-perf-no-secty-arm64.yml
taf/docker-compose-taf-perf-no-secty.yml
taf/docker-compose-taf-perf.yml
taf/docker-compose-taf.yml

fixes https://github.com/edgexfoundry/edgex-compose/issues/494
When running `make run ds-virtual`, the edge-ui-go will fail to run up with errors like
"open /tmp/edgex/secrets/ui/secrets-token.json: no such file or directory"
The root of this error is from the missing secret volume mount in add-security.yml
This commit fixes this,

fix: the edge-ui-go cannot run up due to missing secret volumes
