Jenkinsfile
TAF smoke tests are not enabled
TAF Smoke tests now enabled
no
=> build: Add Jenkinsfile to enable TAF smoke tests are run.

compose-builder/add-mqtt-messagebus.yml, compose-builder/docker-compose-base.yml, releases/pre-release/docker-compose-pre-release-arm64.yml, releases/pre-release/docker-compose-pre-release-no-secty-arm64.yml, releases/pre-release/docker-compose-pre-release-no-secty.yml, releases/pre-release/docker-compose-pre-release.yml, releases/pre-release/taf/docker-compose-taf-arm64.yml, releases/pre-release/taf/docker-compose-taf-no-secty-arm64.yml, releases/pre-release/taf/docker-compose-taf-no-secty.yml, releases/pre-release/taf/docker-compose-taf-perf-arm64.yml, releases/pre-release/taf/docker-compose-taf-perf-no-secty-arm64.yml, releases/pre-release/taf/docker-compose-taf-perf-no-secty.yml, releases/pre-release/taf/docker-compose-taf-perf.yml, releases/pre-release/taf/docker-compose-taf.yml
Some updates to ASC Trigger config overrides from recent config changes are missing
All ASC Trigger config overrides now have been updated properly
no
=> fix: Add missing changes to ASC Tigger config overrides

compose-builder/common.env, releases/pre-release/docker-compose-pre-release-arm64.yml, releases/pre-release/docker-compose-pre-release-no-secty-arm64.yml, releases/pre-release/docker-compose-pre-release-no-secty.yml, releases/pre-release/docker-compose-pre-release.yml, releases/pre-release/taf/docker-compose-taf-arm64.yml, releases/pre-release/taf/docker-compose-taf-no-secty-arm64.yml, releases/pre-release/taf/docker-compose-taf-no-secty.yml, releases/pre-release/taf/docker-compose-taf-perf-arm64.yml, releases/pre-release/taf/docker-compose-taf-perf-no-secty-arm64.yml, releases/pre-release/taf/docker-compose-taf-perf-no-secty.yml, releases/pre-release/taf/docker-compose-taf-perf.yml, releases/pre-release/taf/docker-compose-taf.yml
Close #21
Since we modify the config.Clients to use service key, the docker-compose file needs to update the env to meet the changes.
=> feat: Update docker-compose's common env

compose-builder/add-security.yml, releases/pre-release/docker-compose-pre-release-arm64.yml, releases/pre-release/docker-compose-pre-release.yml, releases/pre-release/taf/docker-compose-taf-arm64.yml, releases/pre-release/taf/docker-compose-taf-perf-arm64.yml, releases/pre-release/taf/docker-compose-taf-perf.yml, releases/pre-release/taf/docker-compose-taf.yml
Env override use old school service names.
Env override use service key based names.
Dependent on merging this PR https://github.com/edgexfoundry/edgex-go/pull/3247
=> feat: Update Proxy Setup env overrides for change to use service keys

docker-compose-portainer.yml
Using deprecated version of Portianer
Now using latest Portainer CE
no
=> build: Update to CE version of Portainer

docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
Compose file not rebuilt
Compose file rebuilt with updated dependencies
=> feat: Build latest compose files with updated 3rd party dependencies

compose-builder/add-taf-app-services-secure.yml, compose-builder/add-taf-app-services.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf.yml
scalability-test-mqtt-export fails to stay running due to various issues. See #97 & #98
Resolved duplicate port issue
Resolved Sercets Store issue
Resolved Pipeline execution order issue
Resolved MQTT ClientID issue
=> fix: Resolve start-up issues with scalability-test-mqtt-export in TAF compose

compose-builder/add-security.yml, docker-compose-arm64.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
Override doesn't exist for newly add proxy route for Sys Mgmt Agent
Override now exists for newly add proxy route for Sys Mgmt Agent
=> fix: Add override for Sys Mgmt Agent proxy route Host

compose-builder/Makefile, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> Add device-virtual to KNOWN_SECRETS_LIST

compose-builder/README.md
Step for updating the READMEs missing from the instructions for creating new release.
Step for updating the READMEs to present in the instructions for creating new release.
=> doc: Update release steps in README to include updating the READMEs

compose-builder/add-taf-device-services-mods.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf.yml
=> feat: Add --cp command to device-services in TAF compose files

compose-builder/Makefile, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml
No TAF test compose files are generated with MQTT as the MessageBus
Now new TAF test compose files are generated with MQTT as the MessageBus
=> feat: Generate TAF function test compose files with MQTT MessageBus

compose-builder/.env, docker-compose-arm64.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
Currently using Kong 2.4-alpine 
Now using Kong 2.5 (alpine based image) now that the ARM64 image is available.
=> build: Update to use Kong 2.5

compose-builder/add-security.yml, docker-compose-arm64.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> fix: Set Kong worker default to 1 to reduce the memory consumption

.github/PULL_REQUEST_TEMPLATE.md
Using new PR template base on that approved by TSC. 
Removed items from the new template that are not applicable to this repo.
**N/A**
=> ci: Update to use new PR template

.gitignore
=> build: Add missing .gitignore file

compose-builder/.env, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> build: Update to use latest (working) un-pinned 3rd party versions

compose-builder/Makefile, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf.yml
fix #207
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
=> feat: Add device-camera to taf compose files for TAF test

compose-builder/add-app-rfid-llrp-inventory.yml
=> fix: [Jakarta] Add missing volume for LLRP Inventory app service's data

taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
BREAKING CHANGE: MQTT broker exposed on 127.0.0.1 only after this change
Will be auto-tested.
=> fix(security)!: Ensure that MQTT broker not exposed without password externally (amend)

compose-builder/Makefile, compose-builder/README.md, compose-builder/add-delayed-start-services.yml, compose-builder/add-runtime-token-config-template.yml, compose-builder/common-security.env, compose-builder/gen_runtime_token_config_compose_ext.sh
Relates to: https://github.com/edgexfoundry/edgex-go/issues/3773
- [x ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
=> feat(security): Add delayed start service docker-compose

docker-compose-arm64.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
Fixes: #229
- [x ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
=> fix: add missing common spiffe envs

compose-builder/.env, compose-builder/gen-header, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> build: Pin 3rd party components to patch version

compose-builder/Makefile, compose-builder/README.md, compose-builder/add-asc-metrics-influxdb.yml
=> feat: Add option to include ASC with metrics-influxdb profile

compose-builder/gen-header, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-ui-arm64.yml, docker-compose-no-secty-with-ui.yml, docker-compose-no-secty.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
fixes #214
- [ x I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
=> Fix release name in headers [Ireland]

compose-builder/.env, compose-builder/Makefile, compose-builder/README.md, compose-builder/add-device-onvif-camera.yml, compose-builder/add-device-usb-camera.yml, compose-builder/tui-generator.sh
=> feat: Add new camera device services

compose-builder/.env
Signed-off-by: Kyle Morton <kylex.f.morton@intel.com>
=> fix: Updated to redis v7 #4027

compose-builder/.env, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
Signed-off-by: Kyle Morton <kylex.f.morton@intel.com>
=> fix: Updated to redis v7 with files #4027

compose-builder/Makefile, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> Add Delayed Start services to TAF compose files

compose-builder/Makefile, compose-builder/add-taf-mqtt-broker.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf.yml
=> fix: Add external MQTT broker on Jakarta branch

compose-builder/add-mqtt-messagebus.yml, compose-builder/add-nats-messagebus.yml, compose-builder/docker-compose-base.yml, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> feat: Add new overrides for Core Command MessageQueue

compose-builder/add-secure-mqtt-messagebus.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml
=> fix: Update environment variable for secure mqtt bus

compose-builder/Makefile, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf.yml
=> feat: Replace device-camera with device-onvif-camera

compose-builder/add-device-gpio.yml
```
make run ds-gpio (in compose-builder)
curl -ki http://localhost:59994/api/v2/ping
```
See also #311
=> fix: Move GPIO service to approved documented port (Levski)

compose-builder/.env, compose-builder/Makefile, compose-builder/add-delayed-start-services.yml, compose-builder/add-taf-device-services-mods.yml, docker-compose-arm64.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
related:
https://github.com/edgexfoundry/go-mod-bootstrap/pull/406 https://github.com/edgexfoundry/edgex-go/pull/4255
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
=> refactor!: Remove config options to use default value in 3.0

compose-builder/add-mqtt-messagebus-device-template.yml, compose-builder/add-mqtt-messagebus.yml, compose-builder/add-nats-messagebus.yml, compose-builder/add-secure-mqtt-messagebus.yml, compose-builder/as-common.env, compose-builder/common-sec-stage-gate.env, compose-builder/common.env, compose-builder/docker-compose-base.yml, compose-builder/gen_mqtt_messagebus_compose_ext.sh, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
This PR is dependent on https://github.com/edgexfoundry/edgex-go/pull/4308
TBD
run `make docker` using branch from https://github.com/edgexfoundry/edgex-go/pull/4308
run make run ds-virtual dev from compose builder
Verify all service bootstrap successfully
=> refactor: Adjust compose to fix changes breaking the TAF tests

compose-builder/add-device-gpio.yml
=> revert: [Levski]  Undo the override of Device GPIO's port

compose-builder/add-mqtt-messagebus-device-template.yml, compose-builder/gen_mqtt_messagebus_compose_ext.sh, docker-compose-arm64.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> revert: Remove MESSAGEBUS_TOPICS_SYSTEMEVENTTOPIC workaround

README.md
- [N/A] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [N/A] I have opened a PR for the related docs change (if not, why?)
=> docs: replace hanoi link with link to all branches

compose-builder/docker-compose-base.yml, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
make run dev ds-virtual delayed-start
=> fix: Remove forcing common-config-bootstrap no security

compose-builder/add-security.yml, docker-compose-arm64.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
Start the framework, get consul management token and check for existence of proxy-auth service in the registry.
=> fix: Enable new proxy-auth service to register in service registry

compose-builder/.env, compose-builder/add-security.yml, docker-compose-arm64.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> feat: Update Vault to 1.11 and change to verified publisher image

compose-builder/add-service-secure-template.yml, docker-compose-arm64.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
This commit consumes the breaking change for the variable rename to EDGEX_ADD_PROXY_ROUTE.
Closes #370
<https://github.com/edgexfoundry/edgex-docs/pull/1027>
=> fix: Rename ADD_PROXY_ROUTE to EDGEX_ADD_PROXY_ROUTE

compose-builder/add-device-gpio.yml
=> fix: [main] Correct GPIO Port to be same as documented

compose-builder/add-device-gpio.yml
=> fix: [levski] Correct GPIO Port to be same as documented

compose-builder/add-device-gpio.yml
=> fix: [kamakura] Correct GPIO Port to be same as documented

compose-builder/Makefile, compose-builder/README.md, compose-builder/add-device-bacnet-ip.yml, compose-builder/add-device-bacnet-mstp.yml, compose-builder/gen_secure_compose_ext.sh, compose-builder/tui-generator.sh
Cherry-pick https://github.com/edgexfoundry/edgex-compose/commit/ed91855b0ce04cbbf71c5b408464eeb034d55edf and https://github.com/edgexfoundry/edgex-compose/commit/6be77894abc569a6fa862465c9c083130fcabd1e from main branch
Run ds-bacnet-<ip/mstp> in both secure and non-secure modes.
```
make run ds-bacnet-ip
make run ds-bacnet-ip no-secty
make run ds-bacnet-mstp
make run ds-bacnet-mstp no-secty
```
=> fix: Add ds-bacnet-ip and ds-bacnet-mstp options

compose-builder/.env, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> build: Bump 3rd party container versions

compose-builder/gen-header, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml, taf/docker-compose-taf-no-secty-mqtt-bus.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> docs: Update compose file header for Odessa WIP

compose-builder/add-security.yml, docker-compose-arm64.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-mqtt-bus-arm64.yml, taf/docker-compose-taf-mqtt-bus.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> refactor(napa): Remove unneeded edgex-kong network alias

docker-compose-postgres-no-secty-arm64.yml, docker-compose-postgres-no-secty.yml
closes #457
https://github.com/edgexfoundry/edgex-docs/pull/1369
=> feat: Update compose file for support-cron-scheduler service

docker-compose-postgres-no-secty-arm64.yml, docker-compose-postgres-no-secty.yml
=> fix: Add proper setting in postgres sample

compose-builder/docker-compose-base-postgres.yml
=> fix: Fix wrong database persistence path for PostgreSQL

compose-builder/add-postgres.yml, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose-zero-trust-arm64.yml, docker-compose-zero-trust.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
Postgres uses the host timezone
=> feat: Postgres uses the host timezone

compose-builder/add-device-onvif-camera.yml, docker-compose-arm64.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose-zero-trust-arm64.yml, docker-compose-zero-trust.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> fix: set MESSAGEBUS_HOST to device-onvif-camera

compose-builder/add-modbus-simulator.yml, docker-compose-with-app-sample.yml, docker-compose-zero-trust.yml, docker-compose.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> fix(odessa): Change modbus-simulator image

compose-builder/Makefile, docker-compose-arm64.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose-zero-trust-arm64.yml, docker-compose-zero-trust.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> fix: Incorrect command in mqtt-broker for security performance compose file

compose-builder/Makefile, docker-compose-arm64.yml, docker-compose-no-secty-arm64.yml, docker-compose-no-secty-with-app-sample-arm64.yml, docker-compose-no-secty-with-app-sample.yml, docker-compose-no-secty.yml, docker-compose-with-app-sample-arm64.yml, docker-compose-with-app-sample.yml, docker-compose-zero-trust-arm64.yml, docker-compose-zero-trust.yml, docker-compose.yml, taf/docker-compose-taf-arm64.yml, taf/docker-compose-taf-no-secty-arm64.yml, taf/docker-compose-taf-no-secty.yml, taf/docker-compose-taf-perf-arm64.yml, taf/docker-compose-taf-perf-no-secty-arm64.yml, taf/docker-compose-taf-perf-no-secty.yml, taf/docker-compose-taf-perf.yml, taf/docker-compose-taf.yml
=> fix: Replace convert command with config
